# Generated by Django 5.2.6 on 2025-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('admission', 'Admission Branch'), ('examination', 'Examination Branch'), ('administration', 'Administration Branch'), ('hostel', 'Hostel Branch')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'College Admin'), ('staff', 'Staff'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
